import { PartInput, SheetSettings } from './types';

export const TRANSLATIONS = {
  English: {
    title: "Smart Carpentry Optimizer",
    subtitle: "Sahira Interior",
    sheet_l: "Sheet Length",
    sheet_w: "Sheet Width",
    blade_th: "Kerf (mm)",
    trim_m: "Trim (mm)",
    edge_th: "Edge Banding (mm)",
    stock_sh: "Stock Sheets",
    h_name: "Part Name",
    h_l: "Length",
    h_w: "Width",
    h_grain: "Grain",
    h_qty: "Qty",
    h_edges: "Edges",
    btn_generate: "Generate Layout",
    btn_export: "Export CSV",
    add_row: "Add Row",
    btn_pdf: "Print Layout / PDF",
    btn_json: "Export JSON",
    btn_import_json: "Import JSON",
    btn_more_options: "More Options",
    packing_algo: "Packing Algorithm",
    compare_algos: "Compare Algorithms",
    settings: "Sheet & Optimization Settings",
    cut_list: "Cutting List (Parts)",
    presets: "Load Carpentry Preset",
    efficiency: "Material Efficiency",
    waste: "Overall Waste",
    sheets_used: "Sheets Used",
    total_banding: "Total Edge Banding",
    clear_list: "Clear List",
    unplaced_title: "⚠️ Unplaced Parts (Don't Fit)",
    unplaced_desc: "These parts could not be packed into the available sheet stock. Increase available stock sheets or reduce part count.",
    grain_l: "Lengthwise (Grain ↕)",
    grain_w: "Widthwise (Grain ↔)",
    grain_n: "No Grain (Free ♻)",
    allow_rot: "Allow Rotation",
    edge_select_title: "Configure Edge Banding",
    edge_select_desc: "Select which edges of the part should have edge banding applied. Wooden cut size is automatically reduced by banding thickness.",
    save: "Save",
    top: "Top",
    bottom: "Bottom",
    left: "Left",
    right: "Right",
    utilization_score: "Utilization Score",
    sheet_details: "Sheet Details",
    sheet_waste: "Waste",
    sheet_parts_header: "Parts on this Sheet",
    part_size: "Finished Size",
    cut_size: "Cut Size",
    applied_banding: "Edge Banding"
  },
  Hindi: {
    title: "स्मार्ट बढ़ईगिरी ऑप्टिमाइज़र",
    subtitle: "साहिरा इंटीरियर (Sahira Interior)",
    sheet_l: "शीट लंबाई",
    sheet_w: "शीट चौड़ाई",
    blade_th: "ब्लेड मोटाई (mm)",
    trim_m: "ट्रिम (mm)",
    edge_th: "किनारा एजबेंडिंग (mm)",
    stock_sh: "स्टॉक",
    h_name: "पुर्जे का नाम",
    h_l: "लंबाई",
    h_w: "चौड़ाई",
    h_grain: "ग्रेन (Grain)",
    h_qty: "मात्रा",
    h_edges: "किनारा",
    btn_generate: "लेआउट बनाएँ",
    btn_export: "CSV एक्सपोर्ट",
    add_row: "नया जोड़ें",
    btn_pdf: "प्रिंट लेआउट / PDF",
    btn_json: "JSON एक्सपोर्ट",
    btn_import_json: "JSON आयात",
    btn_more_options: "अधिक विकल्प",
    packing_algo: "पैकिंग एल्गोरिथम",
    compare_algos: "एल्गोरिदम तुलना",
    settings: "शीट और अनुकूलन सेटिंग्स",
    cut_list: "कटिंग सूची (पुर्जे)",
    presets: "कारपेंट्री प्रिसैट लोड करें",
    efficiency: "मटीरियल उपयोग दक्षता",
    waste: "कुल वेस्ट (Waste)",
    sheets_used: "कुल लगी शीटें",
    total_banding: "कुल एजबेंडिंग लंबाई",
    clear_list: "सूची साफ़ करें",
    unplaced_title: "⚠️ बिना पैक हुए पुर्जे",
    unplaced_desc: "ये पुर्जे उपलब्ध स्टॉक शीट्स में फिट नहीं हो सके। स्टॉक शीट्स बढ़ाएं या पुर्जों की संख्या कम करें।",
    grain_l: "लंबाई में (ग्रेन ↕)",
    grain_w: "चौड़ाई में (ग्रेन ↔)",
    grain_n: "बिना ग्रेन (स्वतंत्र ♻)",
    allow_rot: "घुमाएँ (Rotation)",
    edge_select_title: "एजबेंडिंग सेट करें",
    edge_select_desc: "चुनें कि पुर्जे के किन किनारों पर एजबेंडिंग लगाई जानी है। एजबेंडिंग लगाने पर वास्तविक लकड़ी काटने की साइज़ मोटाई के अनुसार घट जाएगी।",
    save: "सुरक्षित करें",
    top: "ऊपर (Top)",
    bottom: "नीचे (Bottom)",
    left: "बायाँ (Left)",
    right: "दायाँ (Right)",
    utilization_score: "मटीरियल उपयोग स्कोर",
    sheet_details: "शीट विवरण",
    sheet_waste: "वेस्ट",
    sheet_parts_header: "इस शीट पर पुर्जे",
    part_size: "तैयार साइज़",
    cut_size: "कटिंग साइज़",
    applied_banding: "एजबेंडिंग"
  }
};

export const DEFAULT_SETTINGS: SheetSettings = {
  unit: 'Inch',
  sheetL: 96.0,
  sheetW: 48.0,
  bladeTh: 3.0, // standard table saw kerf (3mm)
  trimMargin: 10.0, // standard trim margin (10mm)
  edgeTh: 2.0, // standard edge banding (2mm)
  stock: 5,
  algorithm: 'AutoBest',
  sheetCost: 45.0,
  stockItems: [
    { id: 'mat-plywood', name: 'Plywood (प्लाईवुड)', length: 96.0, width: 48.0, cost: 45.0, thickness: 18.0 },
    { id: 'mat-plywood-16', name: 'Commercial Block Board (कमर्शियल बोर्ड)', length: 96.0, width: 48.0, cost: 40.0, thickness: 16.0 },
    { id: 'mat-mdf', name: 'MDF (एमडीएफ)', length: 96.0, width: 48.0, cost: 35.0, thickness: 18.0 },
    { id: 'mat-melamine', name: 'Melamine (मेलामाइन्)', length: 96.0, width: 48.0, cost: 40.0, thickness: 18.0 }
  ],
  edgeBandItems: [
    { id: 'edge-white', name: 'White 0.8mm Edge Band', thickness: 0.8 },
    { id: 'edge-wood', name: 'Woodgrain 2mm Edge Band', thickness: 2.0 }
  ],
  sunmicaItems: [
    { id: 'mica-white-gloss', name: '0.8mm Glossy White (सफ़ेद चमकदार)', thickness: 0.8, code: 'W-Gloss-101' },
    { id: 'mica-wooden-texture', name: '1.0mm Woodgrain Texture (लकड़ी का टेक्सचर)', thickness: 1.0, code: 'Teak-W-204' },
    { id: 'mica-liner-offwhite', name: '0.6mm Off-White Liner (लाइनर माइका)', thickness: 0.6, code: 'OW-Liner-06' }
  ],
  recipes: [
    { id: 'rec-kitchen-01', name: 'MOD_KITCHEN_01', baseMaterialId: 'mat-plywood-16', sideAMicaId: 'mica-white-gloss', sideBMicaId: 'mica-liner-offwhite', calculatedThickness: 17.4 },
    { id: 'rec-wardrobe-02', name: 'MOD_WARD_02', baseMaterialId: 'mat-plywood', sideAMicaId: 'mica-wooden-texture', sideBMicaId: 'mica-wooden-texture', calculatedThickness: 20.0 }
  ],
  respectGrain: true
};

export const INITIAL_PARTS: PartInput[] = [
  {
    id: '1',
    name: 'Wardrobe Side Panel (बायाँ)',
    length: 84.0,
    width: 22.0,
    grain: 'L',
    allowRot: false,
    quantity: 2,
    edges: { T: true, B: true, L: true, R: false },
    materialId: 'mat-plywood'
  },
  {
    id: '2',
    name: 'Wardrobe Shelves (रैक)',
    length: 34.5,
    width: 21.5,
    grain: 'L',
    allowRot: true,
    quantity: 4,
    edges: { T: true, B: false, L: false, R: false },
    materialId: 'mat-mdf'
  },
  {
    id: '3',
    name: 'Drawer Fronts (दराज)',
    length: 11.5,
    width: 33.0,
    grain: 'W',
    allowRot: false,
    quantity: 3,
    edges: { T: true, B: true, L: true, R: true },
    materialId: 'mat-melamine'
  }
];
